vich_uploader:
    db_driver: orm

    mappings:
        filemap:
            uri_prefix: public\assets
            upload_destination : '%kernel.project_dir%/public/assets'
            namer : Vich\UploaderBundle\Naming\UniqidNamer